### ISSUE TITLE
mimir_alertmanager_config  - support for match_re in routes definition

### ISSUE THREAD

**Issue by shybbko** [fgouteroux/terraform-provider-mimir#25]
Based on https://registry.terraform.io/providers/fgouteroux/mimir/latest/docs/resources/alertmanager_config#matchers it seems that only `match` definitions are supported with `match_re` not being available? 

Here's an example on what I mean:

```
route:
  routes:
  - match:
      severity: info
      team: aaa
    receiver: xyz
  - match_re:
      team: bbb
      environment: uat|staging
    receiver: xyz
```
