### ISSUE TITLE
Datasource mimir_rule_group_recording: missing label property

### ISSUE THREAD

**Issue by jrrdev** [fgouteroux/terraform-provider-mimir#27]
When querying a `mimir_rule_group_recording` with labels, Terraform will crash with the following error:

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Invalid address to set: []string{"rule", "0", "labels"}
│ 
│   with data.mimir_rule_group_recording.record,
│   on main.tf line 26, in data "mimir_rule_group_recording" "record":
│   26: data "mimir_rule_group_recording" "record" {
│ 
╵
```

### Recording rule

Recording rule created in Grafana Cloud.
mimirtool output:

```yaml
name: test-eval-group
rules:
    - record: recording_probe_success
      expr: |-
        probe_success
        + on (instance, job, probe, config_version) group_left(org_id, geohash, check_name, region, frequency)
        (
          0 * label_replace(sm_check_info{label_org_id!=""}, "org_id", "$1", "label_org_id", "(.+)")
        )        
      labels:
        recording_success_probe: probe_success
```

### Terraform file

```terraform
provider "mimir" {
  uri = "<redacted>"
  ruler_uri = "<redacted>"
  org_id = "<redacted>"
  username = "<redacted>"
  password = "<redacted>"
  debug = true
}

data "mimir_rule_group_recording" "record" {
  name      = "test-eval-group"
  namespace = "synthetic_monitoring"
}

output "rules" {
  value = data.mimir_rule_group_recording.record
}
```

and then launch `terraform plan`

## Terraform debug output

```
HTTP/1.1 200 OK
Content-Length: 755
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Content-Type: application/yaml
Date: Tue, 19 Mar 2024 14:14:58 GMT
Vary: Accept-Encoding
Via: 1.1 google

name: test-eval-group
rules:
    - record: recording_probe_success
      expr: |-
        probe_success
        + on (instance, job, probe, config_version) group_left(org_id, geohash, check_name, region, frequency)
        (
          0 * label_replace(sm_check_info{label_org_id!=""}, "org_id", "$1", "label_org_id", "(.+)")
        )
      labels:
        recording_success_probe: probe_success
    - record: recording_probe_success_with_hostname
      expr: |-
        recording_probe_success
        + on (instance, job, probe, config_version) group_left(hostname, geohash, check_name, region, frequency, alert_sensitivity)
        (
          0 * label_replace(sm_check_info{label_hostname!=""}, "hostname", "$1", "label_hostname", "(.+)")
        ): timestamp=2024-03-19T15:14:58.773+0100
2024-03-19T15:14:58.773+0100 [INFO]  provider.terraform-provider-mimir_v0.2.5: 2024/03/19 15:14:58 [ERROR] setting state: Invalid address to set: []string{"rule", "0", "labels"}: timestamp=2024-03-19T15:14:58.773+0100
2024-03-19T15:14:58.773+0100 [ERROR] provider.terraform-provider-mimir_v0.2.5: Response contains error diagnostic: @module=sdk.proto tf_proto_version=5.3 diagnostic_detail= diagnostic_severity=ERROR diagnostic_summary="Invalid address to set: []string{"rule", "0", "labels"}" tf_data_source_type=mimir_rule_group_recording tf_provider_addr=registry.terraform.io/fgouteroux/mimir tf_req_id=35864dcf-c7b4-2fdf-3763-c74dcc34462a @caller=github.com/hashicorp/terraform-plugin-go@v0.16.0/tfprotov5/internal/diag/diagnostics.go:58 tf_rpc=ReadDataSource timestamp=2024-03-19T15:14:58.773+0100
2024-03-19T15:14:58.774+0100 [ERROR] vertex "data.mimir_rule_group_recording.record" error: Invalid address to set: []string{"rule", "0", "labels"}
2024-03-19T15:14:58.774+0100 [ERROR] vertex "data.mimir_rule_group_recording.record (expand)" error: Invalid address to set: []string{"rule", "0", "labels"}
```
